services:
  yourls:
    image: guessi/docker-yourls:1.9.2-theme
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./conf/opt/yourls:/opt/yourls
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "30"
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true