services:
  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack'
    environment:
      TZ: 'Asia/Jakarta'
      SERVER_ADMIN: 'gintingari73@gmail.com'
      HTTP_SERVER_NAME: 'link.arigints.my.id'
      HTTPS_SERVER_NAME: 'link.arigints.my.id'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - linkstack:/htdocs
    ports:
      - '8002:80'
      - '8081:443'
    restart: always
    user: root
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true

volumes:
  linkstack: