services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always	
    ports:
      - "8080:80"
    volumes:
      - /data/filebrowser/data:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    #user: 1000:1000
