version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always	
    ports:
      - "8080:80"
    volumes:
      - $HOME/docker-prod/filebrowser/data:/srv
      - $HOME/docker-prod/filebrowser/filebrowser.db:/database.db
      - $HOME/docker-prod/filebrowser/filebrowser.json:/.filebrowser.json
    #user: 1000:1000
