services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 123
    networks:
      - my_shared_network

  app:
    image: nextcloud:stable
    restart: always
    ports:
      - 8000:80
    dns:
      - 192.168.0.1
      - 8.8.8.8
    links:
      - redis
    volumes:
      - /data/docker/nextcloud/config:/var/www/html/config
      - /data/docker/nextcloud/data:/var/www/html/data
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true