services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - ./data/uptime-kuma/:/app/data
     # - ../server:/app/server
      #- ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
