services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /data/docker/wireguard-ui/db:/app/db
      - /etc/wireguard:/etc/wireguard